### ISSUE TITLE
Unecessary conditional in MenuManager.java

### ISSUE THREAD

**Issue by agrawaladityaraj** [COMP2522/project-team-paul#108]
This comparison can just be converted to `if (game.gameOver)`
https://github.com/COMP2522/project-team-paul/blob/1d0825749b63415c33be9b2da431188c772db3a7/src/main/java/org/bcit/comp2522/JaydenJump/MenuManager.java#L194

**Comment by RavdeepAulakh** [comment]
Brian fixed this
