### ISSUE TITLE
This could be done in another method

### ISSUE THREAD

**Issue by JeevanVirk** [COMP2522/project-team-paul#167]
https://github.com/COMP2522/project-team-paul/blob/1d0825749b63415c33be9b2da431188c772db3a7/src/main/java/org/bcit/comp2522/JaydenJump/Player.java#L125

Projectile stuff could be done in another method. I mean there can be another method doing this instead of doing this in draw. This will also lead to code re-usability as you will use draw method in the other method.

**Comment by RavdeepAulakh** [comment]
Method would make this code longer
