### ISSUE TITLE
Using negative moveMent speed!

### ISSUE THREAD

**Issue by JeevanVirk** [COMP2522/project-team-paul#170]
https://github.com/COMP2522/project-team-paul/blob/1d0825749b63415c33be9b2da431188c772db3a7/src/main/java/org/bcit/comp2522/JaydenJump/Player.java#L186

Can we use negative variable? It could be done something as multiplying it with -1.

**Comment by RavdeepAulakh** [comment]
need to do that to make them move in the correct direction
