### ISSUE TITLE
random powerups

### ISSUE THREAD

**Issue by LaurieSolkoski** [COMP2522/project-team-paul#71]
right now powerups are being randomly generated, visually I can't tell which powerup is a tire, jet pack, or an extra life

https://github.com/COMP2522/project-team-paul/blob/1d0825749b63415c33be9b2da431188c772db3a7/src/main/java/org/bcit/comp2522/JaydenJump/PowerUpManager.java#L140

**Comment by RavdeepAulakh** [comment]
Intentional want the player not to know which power up they will get
